{
 "title": "Alerts Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Alerts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT SUM(cpu) FROM logs.metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Memory Events",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT SUM(memory) FROM logs.metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Privilege escalation events",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT SUM(priviledge_escalation) FROM logs.metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "System Alerts",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT date, device_name, data FROM logs.alerts LIMIT 50 "
    }
   ]
  }
 ]
}